name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: make ci (OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [22.3, 21.3]
    steps:
      - uses: actions/checkout@v2
        with:
          otp-version: ${{ matrix.otp }}
      - name: Starting EPMD
        run: epmd -daemon
      - name: Running Tests
        run: make ci
